### PR TITLE
added labels to last 3 leave boxes & resized the added labels & remov…

### PR DESCRIPTION
**Pull request by andrewkykoo**
fixes 
- added labels to the last 3 leave boxes
- formatted spaces and quotes

future improvements
- responsive design

question
- "add info icon": please elaborate on this fix - do you mean creating a container that contains these three leave boxes and has an info icon?

### CODE REVIEW

**Comment by wimpywarlord** [comment]
I will check in the next 6 hours and get back.

Also, Lets connect on [twitter](https://twitter.com/kshitij_dhyani) or [discord](https://discord.gg/dsfM6sWk).

Don't hesitate, to invite your friends to work on the project. Lets keep building something beautiful together.

**Comment by wimpywarlord** [comment]
> **future improvements**
> responsive design

💯  Green signal on this, create a separate issue for this. 

> question
> "add info icon": please elaborate on this fix - do you mean creating a container that contains these three leave boxes and has an info icon?

**Problem**
As of now, the user does not the understand the meaning of these 3 input boxes. These simple plain 3 input boxes, with no context regarding the use. The user gets confused regarding what to put inside these input fields (See image for reference).

as of now

**Solution**
Feel free to improve. I was thinking of the following solutions:
1) Add an info icon, with a hovering tool tip which contains the information regarding the use of these input fields. 

2) Add Labels above the input fields, to give context of usage. 

The context of usage is as follows. 
1) The first input field with sick emoji is for:
Sick Leaves Taken in 2022. 

2) The Second input field is for:
Casual Leaves Taken in 2022

3) The Third input field is for:
Optional Leaves Taken in 2022

The Tool Tip can contain the following Messages. 
1) You receive total 12 sick leaves in a year. 

2) You receive total 8 casual leaves in a year.

3) You receive total 5 sick leaves in a year.

**Design Expectations**
Something similar to these designs are expected.

Try your best to stick to the current color theme.

Screenshot at Apr 05 15-01-46

Screenshot at Apr 05 15-01-54

**Further Discussion**
In future these might be removed, permanently, since the Data will be taken directly from the company and fed to the database, such that the user has 0 hassle in onboarding.

**Comment by andrewkykoo** [comment]
fixes
* added info icon & tool tip for each leave box
* removed repeated codes for Col component and streamlined using .map() method
* set the minimum input value for leave box to 0

**Comment by wimpywarlord** [comment]
[Similar](https://github.com/wimpywarlord/Blue-Sapling-Leave-Tracker/pull/11#issuecomment-1091175481) Code formatting issue here as well, causing problems while code review.

**Pull request closed without merging**
